CREATE DATABASE HOWWORK

USE HOWWORK

CREATE TABLE ADMIN (
    ADMIN_ID            CHAR(10)        PRIMARY KEY,
    ADMIN_PASSWORD      VARCHAR(255)    NOT NULL,
    ADMIN_FULLNAME      VARCHAR(255)    NOT NULL,
    ADMIN_EMAIL         VARCHAR(255)    NOT NULL,
    ADMIN_PHONE         CHAR(10)        NOT NULL,
    ADMIN_POSITION      CHAR(255)       NOT NULL,
    ADMIN_UNIT          CHAR(255)       NOT NULL,
)

CREATE TABLE USER (
    USER_ID            CHAR(10)        PRIMARY KEY,
    USER_PASSWORD      VARCHAR(255)    NOT NULL,
    USER_FULLNAME      VARCHAR(255)    NOT NULL,
    USER_EMAIL         VARCHAR(255)    NOT NULL,
    USER_PHONE         CHAR(10)        NOT NULL,
    USER_POSITION      CHAR(255)       NOT NULL,
    USER_UNIT          CHAR(255)       NOT NULL,
)

CREATE TABLE JOB_TYPE (
    JT_ID       CHAR(6)         PRIMARY KEY,
    JT_NAME     VARCHAR(255)    NOT NULL,
)

CREATE TABLE PROJECT (
    PROJECT_ID
)