import Home from './home'
import { Login, ForgotPassword } from './account'
import {
  AdminHomePage,
  AdminNotifications,
  AdminProjects,
  AdminSummary,
  AdminTasks,
  AdminCreateUser,
  AdminCreateAdmin,
  AdminInformation,
  AdminChangeKey,
  AdminChangePassword,
} from './admin'
import {
  UserHomePage,
  UserNotifications,
  UserTasks,
  UserProjects,
  UserSummary,
  UserInformation,
  UserChangePassword,
  UserChangeKey,
  UserTasksDetail,
  UserProjectsDetail,
} from './user'

export {
  Home,
  Login,
  ForgotPassword,
  AdminHomePage,
  AdminNotifications,
  AdminProjects,
  AdminSummary,
  AdminTasks,
  AdminCreateUser,
  AdminCreateAdmin,
  AdminInformation,
  AdminChangeKey,
  AdminChangePassword,
  UserHomePage,
  UserNotifications,
  UserTasks,
  UserProjects,
  UserSummary,
  UserInformation,
  UserChangePassword,
  UserChangeKey,
  UserTasksDetail,
  UserProjectsDetail,
}
